'use client';
import {useEffect,useState} from 'react';

type Backup={id:string;status:string;storageRef:string|null;sizeBytes:number|null;completedAt:string|null;createdAt:string};
type History={id:string;action:string;metadata:any;createdAt:string};

export default function BackupManager({applicationId}:{applicationId:string}){
 const [backups,setBackups]=useState<Backup[]>([]); const [history,setHistory]=useState<History[]>([]); const [restoreTime,setRestoreTime]=useState(''); const [name,setName]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 async function load(){const [b,h]=await Promise.all([fetch(`/api/applications/${applicationId}/backups`),fetch(`/api/applications/${applicationId}/backups/recover/history`)]);if(b.ok)setBackups((await b.json()).backups||[]);if(h.ok)setHistory((await h.json()).history||[]);}
 useEffect(()=>{load()},[]);
 async function createBackup(){setBusy(true);setMessage('');try{const r=await fetch(`/api/applications/${applicationId}/backups`,{method:'POST'});const x=await r.json();if(!r.ok)throw new Error(x.error||'Backup failed');setMessage(x.backup?.status==='COMPLETED'?'Backup completed.':'Backup started.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Backup failed')}finally{setBusy(false)}}
 async function recover(){setBusy(true);setMessage('');try{const when=new Date(restoreTime);if(!restoreTime||Number.isNaN(when.getTime()))throw new Error('Choose a valid restore time');if(when.getTime()>Date.now()-10*60*1000)throw new Error('Restore time must be at least 10 minutes in the past');const r=await fetch(`/api/applications/${applicationId}/backups/recover`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({restoreTime:when.toISOString(),name:name.trim()||`Recovery ${when.toISOString()}`})});const x=await r.json();if(!r.ok)throw new Error(x.error||'Recovery failed');setMessage('Recovery started. Bridge will not replace the live database automatically.');setName('');await load();}catch(e){setMessage(e instanceof Error?e.message:'Recovery failed')}finally{setBusy(false)}}
 return <div className="card" style={{marginTop:18}}><div className="actions" style={{justifyContent:'space-between'}}><div><h2>Backups & Recovery</h2><p className="muted">Create a backup or start an isolated point-in-time recovery.</p></div><button className="btn" disabled={busy} onClick={createBackup}>Create backup</button></div>{message&&<p className="muted">{message}</p>}
  <h3>Recent backups</h3>{backups.length===0?<p className="muted">No backups yet.</p>:<table className="table"><thead><tr><th>Created</th><th>Status</th><th>Completed</th></tr></thead><tbody>{backups.map(b=><tr key={b.id}><td>{new Date(b.createdAt).toISOString()}</td><td>{b.status}</td><td>{b.completedAt?new Date(b.completedAt).toISOString():'—'}</td></tr>)}</tbody></table>}
  <h3 style={{marginTop:20}}>Point-in-time recovery</h3><p className="muted">Recovery creates an isolated database. Verify it before any production cutover.</p><div className="actions"><input type="datetime-local" value={restoreTime} onChange={e=>setRestoreTime(e.target.value)}/><input value={name} onChange={e=>setName(e.target.value)} placeholder="Recovery name"/><button className="btn secondary" disabled={busy||!restoreTime} onClick={recover}>Start recovery</button></div>
  <h3 style={{marginTop:20}}>Recovery history</h3>{history.length===0?<p className="muted">No recovery events yet.</p>:<table className="table"><thead><tr><th>Time</th><th>Event</th><th>Recovery</th></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>{new Date(h.createdAt).toISOString()}</td><td>{h.action.replaceAll('BACKUP_RECOVERY_','')}</td><td>{h.metadata?.recoveryId||'—'}</td></tr>)}</tbody></table>}
 </div>;
}
