'use client';
import {useState} from 'react';

type Domain={id:string;hostname:string;status:string;target:string|null;sslActive:boolean;verificationToken:string|null};

export default function DomainManager({applicationId,initialDomains}:{applicationId:string;initialDomains:Domain[]}){
 const [domains,setDomains]=useState(initialDomains); const [hostname,setHostname]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [instructions,setInstructions]=useState<any>(null);
 async function add(){setBusy(true);setMessage('');try{const r=await fetch('/api/domains',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({applicationId,hostname})});const x=await r.json();if(!r.ok)throw new Error(x.error||'Could not add domain');setDomains(d=>[...d,x.domain]);setHostname('');setInstructions(x);setMessage('Domain added. Add the DNS record below, then verify.');}catch(e){setMessage(e instanceof Error?e.message:'Could not add domain')}finally{setBusy(false)}}
 async function verify(id:string){setBusy(true);setMessage('');try{const r=await fetch(`/api/domains/${id}/verify`,{method:'POST'});const x=await r.json();if(x.domain)setDomains(d=>d.map(v=>v.id===id?x.domain:v));if(x.verificationTxt||x.dns)setInstructions(x);setMessage(x.message||x.error||'Verification finished.');}catch(e){setMessage(e instanceof Error?e.message:'Verification failed')}finally{setBusy(false)}}
 async function reconcile(id:string){setBusy(true);setMessage('');try{const r=await fetch(`/api/domains/${id}/reconcile`,{method:'POST'});const x=await r.json();if(!r.ok)throw new Error(x.error||'Reconciliation failed');if(x.domain)setDomains(d=>d.map(v=>v.id===id?x.domain:v));setMessage(x.message||'Domain status refreshed.');}catch(e){setMessage(e instanceof Error?e.message:'Could not refresh domain')}finally{setBusy(false)}}
 return <div className="card" style={{marginTop:18}}><div className="actions" style={{justifyContent:'space-between'}}><div><h2>Domains</h2><p className="muted">Connect a custom domain and activate HTTPS.</p></div></div><div className="actions" style={{margin:'16px 0'}}><input value={hostname} onChange={e=>setHostname(e.target.value)} placeholder="www.example.com" style={{flex:1,minWidth:240}}/><button className="btn" disabled={busy||!hostname.trim()} onClick={add}>Add domain</button></div>{message&&<p className="muted">{message}</p>}{domains.map(d=><div key={d.id} className="card" style={{marginTop:12,padding:16}}><div className="actions" style={{justifyContent:'space-between'}}><div><strong>{d.hostname}</strong><p className="muted" style={{margin:'6px 0'}}>Status: {d.status} · HTTPS: {d.sslActive?'Active':'Pending'}</p></div><div className="actions"><button className="btn secondary" disabled={busy||d.status==='ACTIVE'} onClick={()=>verify(d.id)}>Verify DNS</button><button className="btn secondary" disabled={busy||d.status==='ACTIVE'} onClick={()=>reconcile(d.id)}>Refresh</button></div></div>{d.target&&<p className="muted">Target: {d.target}</p>}</div>)}{instructions&&<div className="card" style={{marginTop:14}}><h3>DNS instructions</h3>{instructions.dns&&<p><strong>{instructions.dns.type}</strong> — {instructions.dns.name} → {instructions.dns.target}</p>}{instructions.verificationTxt&&<p><strong>TXT</strong> — {instructions.verificationTxt.name} → {instructions.verificationTxt.value}</p>}<p className="muted">For an apex/root domain, use your DNS provider's ALIAS/ANAME equivalent when CNAME is not supported.</p></div>}</div>;
}
